[env]
RUST_BACKTRACE = "full"
CMAKE_GENERATOR = "Ninja"
CMAKE_EXPORT_COMPILE_COMMANDS = "1"
CMAKE_BUILD_PARALLEL_LEVEL = "12" # num_cpus::get()
CMAKE_MAKE_PROGRAM = "ninja"

[alias]
br = "build --release"
rr = "run --release"
tr = "test --release"

[build]
target-dir = "ox-build/target"