# OxideMiner/.cargo/config.toml

[env]
RUST_BACKTRACE = "full"
CMAKE_GENERATOR = "Ninja"
CMAKE_EXPORT_COMPILE_COMMANDS = "1"
CMAKE_BUILD_PARALLEL_LEVEL = "num_cpus::get()"
CMAKE_MAKE_PROGRAM = "ninja"
CMAKE_BUILD_TYPE = "RelWithDebInfo"
CMAKE_MSVC_RUNTIME_LIBRARY = "MultiThreadedDLL"   # /MD (release CRT), not /MDd

[alias]
br = "build --release"
rr = "run --release"
tr = "test --release"
c  = "check --all --all-targets --all-features"
mp = "build --profile maxperf"

[build]
target-dir = "ox-build/target"

[profile.dev]
opt-level = 1
