[build]
target-dir = "./ox-build/target"

[env]
CMAKE_GENERATOR = "Ninja"
#CMAKE_GENERATOR = "Visual Studio 17 2022"
CMAKE_BUILD_PARALLEL_LEVEL = "10"
CMAKE_MAKE_PROGRAM = "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"
RUST_BACKTRACE = "full"

[alias]
br = "build --release"
rr = "run --release"
tr = "test --release"
